# Netlify 배포 설정 파일

[build]
  # 빌드 명령어 (정적 사이트이므로 별도 빌드 불필요)
  command = "echo 'No build required for static site'"
  
  # 배포할 디렉토리
  publish = "."

[build.environment]
  # Node.js 버전 (필요시)
  NODE_VERSION = "18"

# 리다이렉트 설정
[[redirects]]
  # SPA 라우팅을 위한 설정 (필요시)
  from = "/search"
  to = "/?search=:query"
  status = 301

[[redirects]]
  # 404 페이지 처리
  from = "/*"
  to = "/404.html"
  status = 404

# 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    # 보안 헤더
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 캐시 설정
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    # HTML 파일은 짧은 캐시
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    # CSS 파일 장기 캐시
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    # JavaScript 파일 장기 캐시
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    # 이미지 파일 장기 캐시
    Cache-Control = "public, max-age=31536000, immutable"

# 압축 설정
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# 폼 처리 (연락처 폼 등에 사용)
[forms]
  # Netlify Forms 활성화
  # 실제 폼이 있을 때 사용

# 기능 설정
[functions]
  # Netlify Functions 디렉토리 (필요시)
  directory = "netlify/functions"

# 환경별 설정
[context.production]
  command = "echo 'Production build'"
  
[context.deploy-preview]
  command = "echo 'Deploy preview build'"
  
[context.branch-deploy]
  command = "echo 'Branch deploy build'"

# Edge Functions (필요시)
# [[edge_functions]]
#   function = "hello"
#   path = "/api/hello"
